In [1]:
import csv
import requests

import numpy as np
import pandas as pd
import ast

## PTB XL - Dataset Exploration
References: http://webimatics.univ-lyon1.fr/scp-ecg/, https://www.nature.com/articles/s41597-020-0495-6#ref-CR3

### Classes and Categories

There are **71** unique SCP-ECG statements used in the dataset. We categorize them by assigning each statement to one or more of the following categories: **diagnostic, form and rhythm** statements. There are **44 different diagnostic** statements, **19 different form** statements describing the form of the ECG signal, where 4 statements for diagnostic and form coincide, **12 different non-overlapping rhythm statements** describing the cardiac rhythm

| <img src="https://media.springernature.com/lw685/springer-static/image/art%3A10.1038%2Fs41597-020-0495-6/MediaObjects/41597_2020_495_Fig1_HTML.png" alt="Classes" style="width: 300px;"/> | <img src="https://media.springernature.com/lw685/springer-static/image/art%3A10.1038%2Fs41597-020-0495-6/MediaObjects/41597_2020_495_Fig4_HTML.png" alt="Categories" style="width: 300px;"/>   |
|------|------|

### Parent Classes (Class Hierarchy)
For diagnostic statements we provide a hierarchy of superclasses and subclasses that can be used to train classification algorithms on a set of broader categories instead of the original fine-grained diagnostic labels

### Likelihood

The likelihood ranges from 0 to 100 conveying the certainty the cardiologist (if the diagnosing cardiologist is very certain about a statement). For form and rhythm statements or in cases where no likelihood information was available, the corresponding likelihood was set to zero. 

### Diagnostic/Form/Rhythm Classes
- Diagnostic: https://www.nature.com/articles/s41597-020-0495-6/tables/7
- Form: https://www.nature.com/articles/s41597-020-0495-6/tables/8
- Rhythm: https://www.nature.com/articles/s41597-020-0495-6/tables/9

In [2]:
# PTB-XL Dataset
ptb_dataset_link = "https://www.physionet.org/files/ptb-xl/1.0.1/ptbxl_database.csv?download"
# PTB-XL SCP Classes
ptb_classes_link = "https://www.physionet.org/files/ptb-xl/1.0.1/scp_statements.csv"

In [3]:
# Get all classes from ptb_database
ptb_classes = []
with requests.Session() as s:
    download = s.get(ptb_classes_link)
    decoded_content = download.content.decode('utf-8')
    cr = csv.reader(decoded_content.splitlines(), delimiter=',')
    my_list = list(cr)
    for row in my_list:
        ptb_classes.append(row)

In [4]:
all_ptb_short = []
diagnostic_ptb_short = []
form_ptb_short = []
rhythm_ptb_short = []
#print(ptb_classes)
for ptb_clss in ptb_classes[1:]:
    all_ptb_short.append(ptb_clss[0])
    if ptb_clss[2] == '1.0':
        diagnostic_ptb_short.append(ptb_clss[0])
    if ptb_clss[3] == '1.0':
        form_ptb_short.append(ptb_clss[0])
    if ptb_clss[4] == '1.0':
        rhythm_ptb_short.append(ptb_clss[0])

In [5]:
print('PTB has', len(all_ptb_short), 'classes'\
      '( DIAGNOSTIC [', len(diagnostic_ptb_short),
      '] FORM [',len(form_ptb_short),
      '] RHYTHM [', len(rhythm_ptb_short), '] )')

PTB has 71 classes( DIAGNOSTIC [ 44 ] FORM [ 19 ] RHYTHM [ 12 ] )

In [6]:
# What are form and rhythm classes???
print(form_ptb_short)

['NDT', 'NST_', 'DIG', 'LNGQT', 'ABQRS', 'PVC', 'STD_', 'VCLVH', 'QWAVE', 'LOWT', 'NT_', 'PAC', 'LPR', 'INVT', 'LVOLT', 'HVOLT', 'TAB_', 'STE_', 'PRC(S)']

In [7]:
# 	# Records	Description	Superclass	Subclass
diagnostic = """LAFB	1626	left anterior fascicular block	CD	LAFB/LPFB
IRBBB	1118	incomplete right bundle branch block	CD	IRBBB
AVB	797	first degree AV block	CD	_AVB
IVCD	789	non-specific intraventricular conduction disturbance (block)	CD	IVCD
CRBBB	542	complete right bundle branch block	CD	CRBBB
CLBBB	536	complete left bundle branch block	CD	CLBBB
LPFB	177	left posterior fascicular block	CD	LAFB/LPFB
WPW	80	Wolff-Parkinson-White syndrome	CD	WPW
ILBBB	77	incomplete left bundle branch block	CD	ILBBB
3AVB	16	third degree AV block	CD	_AVB
2AVB	14	second degree AV block	CD	_AVB
LVH	2137	left ventricular hypertrophy	HYP	LVH
LAO/LAE	427	left atrial overload/enlargement	HYP	LAO/LAE
RVH	126	right ventricular hypertrophy	HYP	RVH
RAO/RAE	99	right atrial overload/enlargement	HYP	RAO/RAE
SEHYP	30	septal hypertrophy	HYP	SEHYP
IMI	2685	inferior myocardial infarction	MI	IMI
ASMI	2363	anteroseptal myocardial infarction	MI	AMI
ILMI	479	inferolateral myocardial infarction	MI	IMI
AMI	354	anterior myocardial infarction	MI	AMI
ALMI	290	anterolateral myocardial infarction	MI	AMI
INJAS	215	subendocardial injury in anteroseptal leads	MI	AMI
LMI	201	lateral myocardial infarction	MI	LMI
INJAL	148	subendocardial injury in anterolateral leads	MI	AMI
IPLMI	51	inferoposterolateral myocardial infarction	MI	IMI
IPMI	33	inferoposterior myocardial infarction	MI	IMI
INJIN	18	subendocardial injury in inferior leads	MI	IMI
PMI	17	posterior myocardial infarction	MI	PMI
INJLA	17	subendocardial injury in lateral leads	MI	AMI
INJIL	15	subendocardial injury in inferolateral leads	MI	IMI
NORM	9528	normal ECG	NORM	NORM
NDT	1829	non-diagnostic T abnormalities	STTC	STTC
NST_	770	non-specific ST changes	STTC	NST_
DIG	181	digitalis-effect	STTC	STTC
LNGQT	118	long QT-interval	STTC	STTC
ISC_	1275	non-specific ischemic	STTC	ISC_
ISCAL	660	ischemic in anterolateral leads	STTC	ISCA
ISCIN	219	ischemic in inferior leads	STTC	ISCI
ISCIL	179	ischemic in inferolateral leads	STTC	ISCI
ISCAS	170	ischemic in anteroseptal leads	STTC	ISCA
ISCLA	142	ischemic in lateral leads	STTC	ISCA
ANEUR	104	ST-T changes compatible with ventricular aneurysm	STTC	STTC
EL	97	electrolytic disturbance or drug (former EDIS)	STTC	STTC
ISCAN	44	ischemic in anterior leads	STTC	ISCA"""
# # Records	Description
form = 	"""NDT	1829	non-diagnostic T abnormalities
NST_	770	non-specific ST changes
DIG	181	digitalis-effect
LNGQT	118	long QT-interval
ABQRS	3327	abnormal QRS
PVC	1146	ventricular premature complex
STD_	1009	non-specific ST depression
VCLVH	875	voltage criteria (QRS) for left ventricular hypertrophy
QWAVE	548	Q waves present
LOWT	438	low amplitude T-waves
NT_	424	non-specific T-wave changes
PAC	398	atrial premature complex
LPR	340	prolonged PR interval
INVT	294	inverted T-waves
LVOLT	182	low QRS voltages in the frontal and horizontal leads
HVOLT	62	high QRS voltage
TAB_	35	T-wave abnormality
STE_	28	non-specific ST elevation
PRC(S)	10	premature complex(es)"""
# # Records	Description
rhythm ="""SR	16782	sinus rhythm
AFIB	1514	atrial fibrillation
STACH	826	sinus tachycardia
SARRH	772	sinus arrhythmia
SBRAD	637	sinus bradycardia
PACE	296	normal functioning artificial pacemaker
SVARR	157	supraventricular arrhythmia
BIGU	82	bigeminal pattern (unknown origin, SV or Ventricular)
AFLT	73	atrial flutter
SVTAC	27	supraventricular tachycardia
PSVT	24	paroxysmal supraventricular tachycardia
TRIGU	20	trigeminal pattern (unknown origin, SV or Ventricular)"""

diagnostic_superclasses="""NORM	Normal ECG
CD	Conduction Disturbance
MI	Myocardial Infarction
HYP	Hypertrophy
STTC	ST/T change"""
diagnostic_subclasses="""NORM	NORM	Normal ECG
CD	LAFB/LPFB	left anterior/left posterior fascicular block
CD	IRBBB	incomplete right bundle branch block
CD	ILBBB	incomplete left bundle branch block
CD	CLBBB	complete left bundle branch block
CD	CRBBB	complete right bundle branch block
CD	_AVB	AV block
CD	IVCB	non-specific intraventricular conduction disturbance (block)
CD	WPW	Wolff-Parkinson-White syndrome
HYP	LVH	left ventricular hypertrophy
HYP	RHV	right ventricular hypertrophy
HYP	LAO/LAE	left atrial overload/enlargement
HYP	RAO/RAE	right atrial overload/enlargement
HYP	SEHYP	septal hypertrophy
MI	AMI	anterior myocardial infarction
MI	IMI	inferior myocardial infarction
MI	LMI	lateral myocardial infarction
MI	PMI	posterior myocardial infarction
STTC	ISCA	ischemic in anterior leads
STTC	ISCI	ischemic in inferior leads
STTC	ISC_	non-specific ischemic
STTC	STTC	ST-T changes
STTC	NST_	non-specific ST changes"""
heart_angle="""UNK	Unknown	8505
MID	Normal axis	7687
LAD	Left axis deviation	3764
ALAD	Abnormal LAD, extreme left axis deviation	1382
RAD	Right axis deviation	221
ARAD	Abnormal RAD, extreme right axis deviation	122
AXL	Horizontal axis	102
AXR	Vertical axis	51
SAG	Saggital type (S1-S2-S3 Pattern)	3"""

diagnostic_superclasses = [r.split('\t') for r in diagnostic_superclasses.split('\n')]
diagnostic_subclasses = [r.split('\t') for r in diagnostic_subclasses.split('\n')]
diagnostic_labels = [[r.split('\t')[0], r.split('\t')[-1], r.split('\t')[-2], r.split('\t')[-3]]
                     for r in diagnostic.split('\n')]
form = [[r.split('\t')[0], r.split('\t')[2]] for r in form.split('\n')]
rhythm = [[r.split('\t')[0], r.split('\t')[2]] for r in rhythm.split('\n')]
heart_angle = [[r.split('\t')[0], r.split('\t')[1]] for r in heart_angle.split('\n')]

In [8]:
display("FORM", form, "RYTHM", rhythm, "ANGLE", heart_angle, "DIAGNOSTIC", diagnostic_labels)

'FORM'

[['NDT', 'non-diagnostic T abnormalities'],
 ['NST_', 'non-specific ST changes'],
 ['DIG', 'digitalis-effect'],
 ['LNGQT', 'long QT-interval'],
 ['ABQRS', 'abnormal QRS'],
 ['PVC', 'ventricular premature complex'],
 ['STD_', 'non-specific ST depression'],
 ['VCLVH', 'voltage criteria (QRS) for left ventricular hypertrophy'],
 ['QWAVE', 'Q waves present'],
 ['LOWT', 'low amplitude T-waves'],
 ['NT_', 'non-specific T-wave changes'],
 ['PAC', 'atrial premature complex'],
 ['LPR', 'prolonged PR interval'],
 ['INVT', 'inverted T-waves'],
 ['LVOLT', 'low QRS voltages in the frontal and horizontal leads'],
 ['HVOLT', 'high QRS voltage'],
 ['TAB_', 'T-wave abnormality'],
 ['STE_', 'non-specific ST elevation'],
 ['PRC(S)', 'premature complex(es)']]

'RYTHM'

[['SR', 'sinus rhythm'],
 ['AFIB', 'atrial fibrillation'],
 ['STACH', 'sinus tachycardia'],
 ['SARRH', 'sinus arrhythmia'],
 ['SBRAD', 'sinus bradycardia'],
 ['PACE', 'normal functioning artificial pacemaker'],
 ['SVARR', 'supraventricular arrhythmia'],
 ['BIGU', 'bigeminal pattern (unknown origin, SV or Ventricular)'],
 ['AFLT', 'atrial flutter'],
 ['SVTAC', 'supraventricular tachycardia'],
 ['PSVT', 'paroxysmal supraventricular tachycardia'],
 ['TRIGU', 'trigeminal pattern (unknown origin, SV or Ventricular)']]

'ANGLE'

[['UNK', 'Unknown'],
 ['MID', 'Normal axis'],
 ['LAD', 'Left axis deviation'],
 ['ALAD', 'Abnormal LAD, extreme left axis deviation'],
 ['RAD', 'Right axis deviation'],
 ['ARAD', 'Abnormal RAD, extreme right axis deviation'],
 ['AXL', 'Horizontal axis'],
 ['AXR', 'Vertical axis'],
 ['SAG', 'Saggital type (S1-S2-S3 Pattern)']]

'DIAGNOSTIC'

[['LAFB', 'LAFB/LPFB', 'CD', 'left anterior fascicular block'],
 ['IRBBB', 'IRBBB', 'CD', 'incomplete right bundle branch block'],
 ['AVB', '_AVB', 'CD', 'first degree AV block'],
 ['IVCD',
  'IVCD',
  'CD',
  'non-specific intraventricular conduction disturbance (block)'],
 ['CRBBB', 'CRBBB', 'CD', 'complete right bundle branch block'],
 ['CLBBB', 'CLBBB', 'CD', 'complete left bundle branch block'],
 ['LPFB', 'LAFB/LPFB', 'CD', 'left posterior fascicular block'],
 ['WPW', 'WPW', 'CD', 'Wolff-Parkinson-White syndrome'],
 ['ILBBB', 'ILBBB', 'CD', 'incomplete left bundle branch block'],
 ['3AVB', '_AVB', 'CD', 'third degree AV block'],
 ['2AVB', '_AVB', 'CD', 'second degree AV block'],
 ['LVH', 'LVH', 'HYP', 'left ventricular hypertrophy'],
 ['LAO/LAE', 'LAO/LAE', 'HYP', 'left atrial overload/enlargement'],
 ['RVH', 'RVH', 'HYP', 'right ventricular hypertrophy'],
 ['RAO/RAE', 'RAO/RAE', 'HYP', 'right atrial overload/enlargement'],
 ['SEHYP', 'SEHYP', 'HYP', 'septal hypertrophy'],
 ['IMI', 'IMI', 'MI', 'inferior myocardial infarction'],
 ['ASMI', 'AMI', 'MI', 'anteroseptal myocardial infarction'],
 ['ILMI', 'IMI', 'MI', 'inferolateral myocardial infarction'],
 ['AMI', 'AMI', 'MI', 'anterior myocardial infarction'],
 ['ALMI', 'AMI', 'MI', 'anterolateral myocardial infarction'],
 ['INJAS', 'AMI', 'MI', 'subendocardial injury in anteroseptal leads'],
 ['LMI', 'LMI', 'MI', 'lateral myocardial infarction'],
 ['INJAL', 'AMI', 'MI', 'subendocardial injury in anterolateral leads'],
 ['IPLMI', 'IMI', 'MI', 'inferoposterolateral myocardial infarction'],
 ['IPMI', 'IMI', 'MI', 'inferoposterior myocardial infarction'],
 ['INJIN', 'IMI', 'MI', 'subendocardial injury in inferior leads'],
 ['PMI', 'PMI', 'MI', 'posterior myocardial infarction'],
 ['INJLA', 'AMI', 'MI', 'subendocardial injury in lateral leads'],
 ['INJIL', 'IMI', 'MI', 'subendocardial injury in inferolateral leads'],
 ['NORM', 'NORM', 'NORM', 'normal ECG'],
 ['NDT', 'STTC', 'STTC', 'non-diagnostic T abnormalities'],
 ['NST_', 'NST_', 'STTC', 'non-specific ST changes'],
 ['DIG', 'STTC', 'STTC', 'digitalis-effect'],
 ['LNGQT', 'STTC', 'STTC', 'long QT-interval'],
 ['ISC_', 'ISC_', 'STTC', 'non-specific ischemic'],
 ['ISCAL', 'ISCA', 'STTC', 'ischemic in anterolateral leads'],
 ['ISCIN', 'ISCI', 'STTC', 'ischemic in inferior leads'],
 ['ISCIL', 'ISCI', 'STTC', 'ischemic in inferolateral leads'],
 ['ISCAS', 'ISCA', 'STTC', 'ischemic in anteroseptal leads'],
 ['ISCLA', 'ISCA', 'STTC', 'ischemic in lateral leads'],
 ['ANEUR',
  'STTC',
  'STTC',
  'ST-T changes compatible with ventricular aneurysm'],
 ['EL', 'STTC', 'STTC', 'electrolytic disturbance or drug (former EDIS)'],
 ['ISCAN', 'ISCA', 'STTC', 'ischemic in anterior leads']]

In [9]:
# Download the original physionet classes file
ptb_info_file = "https://www.physionet.org/files/ptb-xl/1.0.1/ptbxl_database.csv?download"
with requests.Session() as s:
    download = s.get(ptb_info_file)
    decoded_content = download.content.decode('utf-8')
    cr = csv.reader(decoded_content.splitlines(), delimiter=',')
    ptb_info = list(cr)

In [10]:
columns = ptb_info[0]
data = []
rows = []
for row in ptb_info[1:]:
    data.append(row[1:])
    rows.append(row[0])
ptb_info_df = pd.DataFrame(data, index=rows, columns=columns[1:])

ptb_info_df

,patient_id,age,sex,height,weight,nurse,site,device,recording_date,report,...,validated_by_human,baseline_drift,static_noise,burst_noise,electrodes_problems,extra_beats,pacemaker,strat_fold,filename_lr,filename_hr
1,15709.0,56.0,1,,63.0,2.0,0.0,CS-12 E,1984-11-09 09:17:34,sinusrhythmus periphere niederspannung,...,True,,", I-V1,",,,,,3,records100/00000/00001_lr,records500/00000/00001_hr
2,13243.0,19.0,0,,70.0,2.0,0.0,CS-12 E,1984-11-14 12:55:37,sinusbradykardie sonst normales ekg,...,True,,,,,,,2,records100/00000/00002_lr,records500/00000/00002_hr
3,20372.0,37.0,1,,69.0,2.0,0.0,CS-12 E,1984-11-15 12:49:10,sinusrhythmus normales ekg,...,True,,,,,,,5,records100/00000/00003_lr,records500/00000/00003_hr
4,17014.0,24.0,0,,82.0,2.0,0.0,CS-12 E,1984-11-15 13:44:57,sinusrhythmus normales ekg,...,True,", II,III,AVF",,,,,,3,records100/00000/00004_lr,records500/00000/00004_hr
5,17448.0,19.0,1,,70.0,2.0,0.0,CS-12 E,1984-11-17 10:43:15,sinusrhythmus normales ekg,...,True,", III,AVR,AVF",,,,,,4,records100/00000/00005_lr,records500/00000/00005_hr
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21833,17180.0,67.0,1,,,1.0,2.0,AT-60 3,2001-05-31 09:14:35,ventrikulÄre extrasystole(n) sinustachykardie ...,...,True,,", alles,",,,1ES,,7,records100/21000/21833_lr,records500/21000/21833_hr
21834,20703.0,93.0,0,,,1.0,2.0,AT-60 3,2001-06-05 11:33:39,sinusrhythmus lagetyp normal qrs(t) abnorm ...,...,True,,,,,,,4,records100/21000/21834_lr,records500/21000/21834_hr
21835,19311.0,59.0,1,,,1.0,2.0,AT-60 3,2001-06-08 10:30:27,sinusrhythmus lagetyp normal t abnorm in anter...,...,True,,", I-AVR,",,,,,2,records100/21000/21835_lr,records500/21000/21835_hr
21836,8873.0,64.0,1,,,1.0,2.0,AT-60 3,2001-06-09 18:21:49,supraventrikulÄre extrasystole(n) sinusrhythmu...,...,True,,,,,SVES,,8,records100/21000/21836_lr,records500/21000/21836_hr
21837,11744.0,68.0,0,,,1.0,2.0,AT-60 3,2001-06-11 16:43:01,sinusrhythmus p-sinistrocardiale lagetyp norma...,...,True,,", I-AVL,",,,,,9,records100/21000/21837_lr,records500/21000/21837_hr

In [11]:
# Now we want to get the ptb class names to the snomed ids 

### Here is some strange stuff:

# To summarize this long email - it is so important that you go back to the source data and look
# at how it is generated, and be appropriately skeptical of any dataset you are given. 
# In this case you have misinterpreted 0.0 as zero likelihood - which is not what the documentation
# of that data indicates. (Yes - NaN should have been used, instead of 0.0, but that was not our choice
# - we did not create that dataset). But let's back up to the larger question ...

# --> SR is always zero

# The likelihood ranges from 0 to 100 conveying the certainty the cardiologist (if the diagnosing
# cardiologist is very certain about a statement). For form and rhythm statements or in cases where
# no likelihood information was available, the corresponding likelihood was set to zero.

# Subject ID: 77 has a report of "sinusrhythmus unvollständiger rechtsschenkelblock", which translates
# as "sinus rhythm incomplete right bundle branch block", and the SCP Code = {'AMI': 50.0, 'IRBBB':
# 100.0, 'SR': 0.0}.  You can certainly be in sinus rhythm and also have an incomplete RBBB.

## Physionet 2020 Challenge Classes (DX_MAP)

### Organizer Description
Each ECG recording has one or more labels from different type of abnormalities in SNOMED-CT codes. The full list of diagnoses for the challenge has been posted here as a 3 column CSV file: Long-form description, corresponding SNOMED-CT code, abbreviation. Although these descriptions apply to all training data there may be fewer classes in the test data, and in different proportions. However, every class in the test data will be represented in the training data.

Source: http://bioportal.bioontology.org/ontologies/SNOMEDCT

In [12]:
dx_map_link_all = "https://raw.githubusercontent.com/physionetchallenges/" \
    "physionetchallenges.github.io/master/2020/Dx_map.csv"

dx_map_link_scored = "https://raw.githubusercontent.com/physionetchallenges/" \
    "evaluation-2020/master/dx_mapping_scored.csv"

dx_map_link_unscored = "https://raw.githubusercontent.com/physionetchallenges/" \
    "evaluation-2020/master/dx_mapping_unscored.csv"

In [13]:
def get_dx_map_classes(link):
    dx_map_classes = []
    with requests.Session() as s:
        download = s.get(link)
        decoded_content = download.content.decode('utf-8')
        cr = csv.reader(decoded_content.splitlines(), delimiter=',')
        dx_map_classes = list(cr)
    return dx_map_classes

dx_map_all = get_dx_map_classes(dx_map_link_all)
dx_map_scored = get_dx_map_classes(dx_map_link_scored)
dx_map_unscored = get_dx_map_classes(dx_map_link_unscored)

In [14]:
all_dx_map_short = []
for dx_map_clss in dx_map_all[1:]:
    all_dx_map_short.append(dx_map_clss[-1])

scored_dx_map_short = []
for dx_map_clss in dx_map_scored[1:]:
    scored_dx_map_short.append(dx_map_clss[2])
    
unscored_dx_map_short = []
for dx_map_clss in dx_map_unscored[1:]:
    unscored_dx_map_short.append(dx_map_clss[2])

In [15]:
print('Challenge has', len(all_dx_map_short),
      'classes, with scored:', len(scored_dx_map_short), "and unscored:", len(unscored_dx_map_short))

Challenge has 111 classes, with scored: 27 and unscored: 84

## SNOMED-CT Names/Classes

There are some strange terms using the snomed system. For example they differentiate between:
- (finding): Clinical finding: normal/abnormal observations, judgments, or assessments of patients
- (disorder): Disorder: always and necessarily an abnormal clinical state

What does this mean for our classes in the challenge? - I do not know.

In [16]:
# Let's take a look all the snomed ids
# Read all the header files and get all snomeds
import sys
sys.path.append('../utils/')
from import_challenge2020 import get_meta_from_header
import pathlib as pl

clss_someds = []
for file in pl.Path('../utils/temp/').iterdir():
    if file.name.split('.')[-1] == 'hea':
        
        clss_someds.append(get_meta_from_header(open(file).readlines())[-1])

In [17]:
all_snomeds_data = np.unique(np.concatenate(clss_someds).ravel())

In [18]:
# For every snomed id in the dataset, get the corresponding snomed description from remote

baseUrl = 'https://browser.ihtsdotools.org/snowstorm/snomed-ct'
edition = 'MAIN'
version = '2019-07-31'

from urllib.request import urlopen
import json
import re

def getConceptById(snomed_id):
    url = baseUrl + '/browser/' + edition + '/' + version + '/concepts/' + snomed_id
    print(url)
    response = urlopen(url).read()
    data = json.loads(response.decode('utf-8'))

    return data['fsn']['term']

def getDescriptionById(snomed_id):
    url = baseUrl + '/' + edition + '/' + version + '/descriptions/' + snomed_id
    print(url)
    response = urlopen(url).read()
    data = json.loads(response.decode('utf-8'))

    return data['term']

def formatConcept(snomed_desc):
    snomed_desc.lower().replace('(disorder)', '').replace('(finding)', '').strip()
    groups = re.split(r"\((\w+)\)", snomed_desc.replace('observable entity',
                                                     'observable'))[:-1]
    concept = groups[0].lower()
    concept = concept.replace('electrocardiographic:', '')
    concept = concept.replace('electrocardiographic', '')
    concept = concept.replace('on electrocardiogram', '')
    concept = concept.replace('electrocardiogram:', '')
    concept = concept.replace('electrocardiogram', '')
     
    concept = concept.replace('of heart', '')
    concept = concept.lower().strip()
    
    return concept

In [19]:
concepts = {}
for a in all_snomeds_data:
    concepts[str(a)] = formatConcept(getConceptById(str(a)))

https://browser.ihtsdotools.org/snowstorm/snomed-ct/browser/MAIN/2019-07-31/concepts/368009
https://browser.ihtsdotools.org/snowstorm/snomed-ct/browser/MAIN/2019-07-31/concepts/6374002
https://browser.ihtsdotools.org/snowstorm/snomed-ct/browser/MAIN/2019-07-31/concepts/10370003
https://browser.ihtsdotools.org/snowstorm/snomed-ct/browser/MAIN/2019-07-31/concepts/11157007
https://browser.ihtsdotools.org/snowstorm/snomed-ct/browser/MAIN/2019-07-31/concepts/13640000
https://browser.ihtsdotools.org/snowstorm/snomed-ct/browser/MAIN/2019-07-31/concepts/17338001
https://browser.ihtsdotools.org/snowstorm/snomed-ct/browser/MAIN/2019-07-31/concepts/27885002
https://browser.ihtsdotools.org/snowstorm/snomed-ct/browser/MAIN/2019-07-31/concepts/29320008
https://browser.ihtsdotools.org/snowstorm/snomed-ct/browser/MAIN/2019-07-31/concepts/39732003
https://browser.ihtsdotools.org/snowstorm/snomed-ct/browser/MAIN/2019-07-31/concepts/47665007
https://browser.ihtsdotools.org/snowstorm/snomed-ct/browser/MAIN/2019-07-31/concepts/49260003
https://browser.ihtsdotools.org/snowstorm/snomed-ct/browser/MAIN/2019-07-31/concepts/49578007
https://browser.ihtsdotools.org/snowstorm/snomed-ct/browser/MAIN/2019-07-31/concepts/53741008
https://browser.ihtsdotools.org/snowstorm/snomed-ct/browser/MAIN/2019-07-31/concepts/54016002
https://browser.ihtsdotools.org/snowstorm/snomed-ct/browser/MAIN/2019-07-31/concepts/54329005
https://browser.ihtsdotools.org/snowstorm/snomed-ct/browser/MAIN/2019-07-31/concepts/55930002
https://browser.ihtsdotools.org/snowstorm/snomed-ct/browser/MAIN/2019-07-31/concepts/57054005
https://browser.ihtsdotools.org/snowstorm/snomed-ct/browser/MAIN/2019-07-31/concepts/59118001
https://browser.ihtsdotools.org/snowstorm/snomed-ct/browser/MAIN/2019-07-31/concepts/59931005
https://browser.ihtsdotools.org/snowstorm/snomed-ct/browser/MAIN/2019-07-31/concepts/60423000
https://browser.ihtsdotools.org/snowstorm/snomed-ct/browser/MAIN/2019-07-31/concepts/63593006
https://browser.ihtsdotools.org/snowstorm/snomed-ct/browser/MAIN/2019-07-31/concepts/65778007
https://browser.ihtsdotools.org/snowstorm/snomed-ct/browser/MAIN/2019-07-31/concepts/67198005
https://browser.ihtsdotools.org/snowstorm/snomed-ct/browser/MAIN/2019-07-31/concepts/74390002
https://browser.ihtsdotools.org/snowstorm/snomed-ct/browser/MAIN/2019-07-31/concepts/74615001
https://browser.ihtsdotools.org/snowstorm/snomed-ct/browser/MAIN/2019-07-31/concepts/75532003
https://browser.ihtsdotools.org/snowstorm/snomed-ct/browser/MAIN/2019-07-31/concepts/77867006
https://browser.ihtsdotools.org/snowstorm/snomed-ct/browser/MAIN/2019-07-31/concepts/81898007
https://browser.ihtsdotools.org/snowstorm/snomed-ct/browser/MAIN/2019-07-31/concepts/82226007
https://browser.ihtsdotools.org/snowstorm/snomed-ct/browser/MAIN/2019-07-31/concepts/84114007
https://browser.ihtsdotools.org/snowstorm/snomed-ct/browser/MAIN/2019-07-31/concepts/89792004
https://browser.ihtsdotools.org/snowstorm/snomed-ct/browser/MAIN/2019-07-31/concepts/111288001
https://browser.ihtsdotools.org/snowstorm/snomed-ct/browser/MAIN/2019-07-31/concepts/111975006
https://browser.ihtsdotools.org/snowstorm/snomed-ct/browser/MAIN/2019-07-31/concepts/164861001
https://browser.ihtsdotools.org/snowstorm/snomed-ct/browser/MAIN/2019-07-31/concepts/164865005
https://browser.ihtsdotools.org/snowstorm/snomed-ct/browser/MAIN/2019-07-31/concepts/164867002
https://browser.ihtsdotools.org/snowstorm/snomed-ct/browser/MAIN/2019-07-31/concepts/164873001
https://browser.ihtsdotools.org/snowstorm/snomed-ct/browser/MAIN/2019-07-31/concepts/164884008
https://browser.ihtsdotools.org/snowstorm/snomed-ct/browser/MAIN/2019-07-31/concepts/164889003
https://browser.ihtsdotools.org/snowstorm/snomed-ct/browser/MAIN/2019-07-31/concepts/164890007
https://browser.ihtsdotools.org/snowstorm/snomed-ct/browser/MAIN/2019-07-31/concepts/164895002
https://browser.ihtsdotools.org/snowstorm/snomed-ct/browser/MAIN/2019-07-31/concepts/164896001
https://browser.ihtsdotools.org/snowstorm/snomed-ct/browser/MAIN/2019-07-31/concepts/164909002
https://browser.ihtsdotools.org/snowstorm/snomed-ct/browser/MAIN/2019-07-31/concepts/164917005
https://browser.ihtsdotools.org/snowstorm/snomed-ct/browser/MAIN/2019-07-31/concepts/164921003
https://browser.ihtsdotools.org/snowstorm/snomed-ct/browser/MAIN/2019-07-31/concepts/164930006
https://browser.ihtsdotools.org/snowstorm/snomed-ct/browser/MAIN/2019-07-31/concepts/164931005
https://browser.ihtsdotools.org/snowstorm/snomed-ct/browser/MAIN/2019-07-31/concepts/164934002
https://browser.ihtsdotools.org/snowstorm/snomed-ct/browser/MAIN/2019-07-31/concepts/164937009
https://browser.ihtsdotools.org/snowstorm/snomed-ct/browser/MAIN/2019-07-31/concepts/164947007
https://browser.ihtsdotools.org/snowstorm/snomed-ct/browser/MAIN/2019-07-31/concepts/164951009
https://browser.ihtsdotools.org/snowstorm/snomed-ct/browser/MAIN/2019-07-31/concepts/195042002
https://browser.ihtsdotools.org/snowstorm/snomed-ct/browser/MAIN/2019-07-31/concepts/195060002
https://browser.ihtsdotools.org/snowstorm/snomed-ct/browser/MAIN/2019-07-31/concepts/195080001
https://browser.ihtsdotools.org/snowstorm/snomed-ct/browser/MAIN/2019-07-31/concepts/195101003
https://browser.ihtsdotools.org/snowstorm/snomed-ct/browser/MAIN/2019-07-31/concepts/195126007
https://browser.ihtsdotools.org/snowstorm/snomed-ct/browser/MAIN/2019-07-31/concepts/204384007
https://browser.ihtsdotools.org/snowstorm/snomed-ct/browser/MAIN/2019-07-31/concepts/233917008
https://browser.ihtsdotools.org/snowstorm/snomed-ct/browser/MAIN/2019-07-31/concepts/251120003
https://browser.ihtsdotools.org/snowstorm/snomed-ct/browser/MAIN/2019-07-31/concepts/251139008
https://browser.ihtsdotools.org/snowstorm/snomed-ct/browser/MAIN/2019-07-31/concepts/251146004
https://browser.ihtsdotools.org/snowstorm/snomed-ct/browser/MAIN/2019-07-31/concepts/251164006
https://browser.ihtsdotools.org/snowstorm/snomed-ct/browser/MAIN/2019-07-31/concepts/251168009
https://browser.ihtsdotools.org/snowstorm/snomed-ct/browser/MAIN/2019-07-31/concepts/251170000
https://browser.ihtsdotools.org/snowstorm/snomed-ct/browser/MAIN/2019-07-31/concepts/251173003
https://browser.ihtsdotools.org/snowstorm/snomed-ct/browser/MAIN/2019-07-31/concepts/251180001
https://browser.ihtsdotools.org/snowstorm/snomed-ct/browser/MAIN/2019-07-31/concepts/251182009
https://browser.ihtsdotools.org/snowstorm/snomed-ct/browser/MAIN/2019-07-31/concepts/251200008
https://browser.ihtsdotools.org/snowstorm/snomed-ct/browser/MAIN/2019-07-31/concepts/251259000
https://browser.ihtsdotools.org/snowstorm/snomed-ct/browser/MAIN/2019-07-31/concepts/251266004
https://browser.ihtsdotools.org/snowstorm/snomed-ct/browser/MAIN/2019-07-31/concepts/251268003
https://browser.ihtsdotools.org/snowstorm/snomed-ct/browser/MAIN/2019-07-31/concepts/253339007
https://browser.ihtsdotools.org/snowstorm/snomed-ct/browser/MAIN/2019-07-31/concepts/253352002
https://browser.ihtsdotools.org/snowstorm/snomed-ct/browser/MAIN/2019-07-31/concepts/266249003
https://browser.ihtsdotools.org/snowstorm/snomed-ct/browser/MAIN/2019-07-31/concepts/266257000
https://browser.ihtsdotools.org/snowstorm/snomed-ct/browser/MAIN/2019-07-31/concepts/270492004
https://browser.ihtsdotools.org/snowstorm/snomed-ct/browser/MAIN/2019-07-31/concepts/282825002
https://browser.ihtsdotools.org/snowstorm/snomed-ct/browser/MAIN/2019-07-31/concepts/284470004
https://browser.ihtsdotools.org/snowstorm/snomed-ct/browser/MAIN/2019-07-31/concepts/314208002
https://browser.ihtsdotools.org/snowstorm/snomed-ct/browser/MAIN/2019-07-31/concepts/370365005
https://browser.ihtsdotools.org/snowstorm/snomed-ct/browser/MAIN/2019-07-31/concepts/413444003
https://browser.ihtsdotools.org/snowstorm/snomed-ct/browser/MAIN/2019-07-31/concepts/413844008
https://browser.ihtsdotools.org/snowstorm/snomed-ct/browser/MAIN/2019-07-31/concepts/425419005
https://browser.ihtsdotools.org/snowstorm/snomed-ct/browser/MAIN/2019-07-31/concepts/425623009
https://browser.ihtsdotools.org/snowstorm/snomed-ct/browser/MAIN/2019-07-31/concepts/425856008
https://browser.ihtsdotools.org/snowstorm/snomed-ct/browser/MAIN/2019-07-31/concepts/426177001
https://browser.ihtsdotools.org/snowstorm/snomed-ct/browser/MAIN/2019-07-31/concepts/426434006

https://browser.ihtsdotools.org/snowstorm/snomed-ct/browser/MAIN/2019-07-31/concepts/426627000
https://browser.ihtsdotools.org/snowstorm/snomed-ct/browser/MAIN/2019-07-31/concepts/426648003
https://browser.ihtsdotools.org/snowstorm/snomed-ct/browser/MAIN/2019-07-31/concepts/426664006
https://browser.ihtsdotools.org/snowstorm/snomed-ct/browser/MAIN/2019-07-31/concepts/426749004
https://browser.ihtsdotools.org/snowstorm/snomed-ct/browser/MAIN/2019-07-31/concepts/426761007
https://browser.ihtsdotools.org/snowstorm/snomed-ct/browser/MAIN/2019-07-31/concepts/426783006
https://browser.ihtsdotools.org/snowstorm/snomed-ct/browser/MAIN/2019-07-31/concepts/426995002
https://browser.ihtsdotools.org/snowstorm/snomed-ct/browser/MAIN/2019-07-31/concepts/427084000
https://browser.ihtsdotools.org/snowstorm/snomed-ct/browser/MAIN/2019-07-31/concepts/427172004
https://browser.ihtsdotools.org/snowstorm/snomed-ct/browser/MAIN/2019-07-31/concepts/427393009
https://browser.ihtsdotools.org/snowstorm/snomed-ct/browser/MAIN/2019-07-31/concepts/428417006
https://browser.ihtsdotools.org/snowstorm/snomed-ct/browser/MAIN/2019-07-31/concepts/428750005
https://browser.ihtsdotools.org/snowstorm/snomed-ct/browser/MAIN/2019-07-31/concepts/429622005
https://browser.ihtsdotools.org/snowstorm/snomed-ct/browser/MAIN/2019-07-31/concepts/445118002
https://browser.ihtsdotools.org/snowstorm/snomed-ct/browser/MAIN/2019-07-31/concepts/445211001
https://browser.ihtsdotools.org/snowstorm/snomed-ct/browser/MAIN/2019-07-31/concepts/446358003
https://browser.ihtsdotools.org/snowstorm/snomed-ct/browser/MAIN/2019-07-31/concepts/446813000
https://browser.ihtsdotools.org/snowstorm/snomed-ct/browser/MAIN/2019-07-31/concepts/698247007
https://browser.ihtsdotools.org/snowstorm/snomed-ct/browser/MAIN/2019-07-31/concepts/698252002
https://browser.ihtsdotools.org/snowstorm/snomed-ct/browser/MAIN/2019-07-31/concepts/704997005
https://browser.ihtsdotools.org/snowstorm/snomed-ct/browser/MAIN/2019-07-31/concepts/713422000
https://browser.ihtsdotools.org/snowstorm/snomed-ct/browser/MAIN/2019-07-31/concepts/713426002
https://browser.ihtsdotools.org/snowstorm/snomed-ct/browser/MAIN/2019-07-31/concepts/713427006
https://browser.ihtsdotools.org/snowstorm/snomed-ct/browser/MAIN/2019-07-31/concepts/67741000119109

In [20]:
df = pd.DataFrame(index=concepts.keys(), columns=['SHORT', 'SNOMED', 'PHYSIONET', 'SCORED', 'SET'])

In [21]:
for key in concepts.keys():
    df.loc[key, 'SNOMED'] = concepts[key]

for entry in dx_map_all[1:]:
    df.loc[entry[1], 'PHYSIONET'] = entry[0]
    df.loc[entry[1], 'SHORT'] = entry[-1]
        
for entry in dx_map_scored[1:]:
    df.loc[entry[1], 'SCORED'] = True
    
for entry in dx_map_unscored[1:]:
    df.loc[entry[1], 'SCORED'] = False

In [22]:
# What is wierd - Now we have classes in the dx map that are nan in the SNOMED
# (classes that are not presend in the dataset)
#index = df['SNOMED'].index[df['SNOMED'].apply(np.isnan)]
for unknown in list(df.loc[pd.isna(df["SNOMED"]), :].index):
    df.loc[unknown, 'SNOMED'] = formatConcept(getConceptById(str(unknown)))

In [23]:
with pd.option_context('display.max_rows', None,
                       'display.max_columns', None):
    df = df.sort_values('SCORED', ascending=False)
    display(df)

,SHORT,SNOMED,PHYSIONET,SCORED,SET
426627000,Brady,bradycardia,bradycardia,True,NaN
59118001,RBBB,right bundle branch block,right bundle branch block,True,NaN
164890007,AFL,atrial flutter,atrial flutter,True,NaN
164889003,AF,atrial fibrillation,atrial fibrillation,True,NaN
164917005,QAb,q wave abnormal,qwave abnormal,True,NaN
426177001,SB,sinus bradycardia,sinus bradycardia,True,NaN
284470004,PAC,premature atrial contraction,premature atrial contraction,True,NaN
111975006,LQT,prolonged qt interval,prolonged qt interval,True,NaN
164934002,TAb,t wave abnormal,t wave abnormal,True,NaN
164947007,LPR,prolonged pr interval,prolonged pr interval,True,NaN
270492004,IAVB,first degree atrioventricular block,1st degree av block,True,NaN
426783006,SNR,sinus rhythm,sinus rhythm,True,NaN
427084000,STach,sinus tachycardia,sinus tachycardia,True,NaN
427172004,PVC,premature ventricular contractions,premature ventricular contractions,True,NaN
427393009,SA,sinus arrhythmia,sinus arrhythmia,True,NaN
59931005,TInv,inverted t wave,t wave inversion,True,NaN
63593006,SVPB,supraventricular premature beats,supraventricular premature beats,True,NaN
47665007,RAD,right axis deviation,right axis deviation,True,NaN
698252002,NSIVCB,non-specific intraventricular conduction delay,nonspecific intraventricular conduction disorder,True,NaN
10370003,PR,rhythm from artificial pacing,pacing rhythm,True,NaN
713427006,CRBBB,complete right bundle branch block,complete right bundle branch block,True,NaN
713426002,IRBBB,incomplete right bundle branch block,incomplete right bundle branch block,True,NaN
17338001,VPB,ventricular premature beats,ventricular premature beats,True,NaN
251146004,LQRSV,low qrs voltages,low qrs voltages,True,NaN
39732003,LAD,left axis deviation,left axis deviation,True,NaN
445118002,LAnFB,left anterior fascicular block,left anterior fascicular block,True,NaN
164909002,LBBB,left bundle branch block,left bundle branch block,True,NaN
266257000,TIA,transient ischemic attack,transient ischemic attack,False,NaN
251182009,VPVC,paired ventricular premature complexes,paired ventricular premature complexes,False,NaN
266249003,VH,ventricular hypertrophy,ventricular hypertrophy,False,NaN
282825002,PAF,paroxysmal atrial fibrillation,paroxysmal atrial fibrillation,False,NaN
251200008,ICA,indeterminate cardiac axis,indeterminate cardiac axis,False,NaN
251259000,HTV,high t-voltage,high t-voltage,False,NaN
251180001,VTrig,ventricular trigeminy,ventricular trigeminy,False,NaN
251266004,VPP,ventricular pacing pattern,ventricular pacing pattern,False,NaN
314208002,RAF,rapid atrial fibrillation,rapid atrial fibrillation,False,NaN
370365005,LVS,left ventricular strain,left ventricular strain,False,NaN
253352002,LAA,left atrial abnormality,left atrial abnormality,False,NaN
413444003,AMIs,acute myocardial ischemia,acute myocardial ischemia,False,NaN
253339007,RAAb,right atrial abnormality,right atrial abnormality,False,NaN
251268003,AP,atrial pacing pattern,atrial pacing pattern,False,NaN
368009,HVD,heart valve disorder,heart valve disorder,False,NaN
413844008,CMI,chronic myocardial ischemia,chronic myocardial ischemia,False,NaN
428417006,ERe,early repolarization,early repolarization,False,NaN
713422000,ATach,atrial tachycardia,atrial tachycardia,False,NaN
704997005,ISTD,inferior st segment depression,inferior ST segment depression,False,NaN
698247007,CD,cardiac arrhythmia,cardiac dysrhythmia,False,NaN
446813000,LAH,left atrial hypertrophy,left atrial hypertrophy,False,NaN
446358003,RAH,right atrial hypertrophy,right atrial hypertrophy,False,NaN
445211001,LPFB,left posterior fascicular block,left posterior fascicular block,False,NaN
429622005,STD,st depression,st depression,False,NaN
428750005,NSSTTA,nonspecific st-t abnormality,nonspecific st t abnormality,False,NaN
426995002,JE,junctional escape rhythm,junctional escape,False,NaN
425419005,IIs,inferior ischemia,inferior ischaemia,False,NaN
426761007,SVT,supraventricular tachycardia,supraventricular tachycardia,False,NaN
426749004,CAF,chronic atrial fibrillation,chronic atrial fibrillation,False,NaN
426664006,AJR,accelerated junctional rhythm,accelerated junctional rhythm,False,NaN
426648003,JTach,junctional tachycardia,junctional tachycardia,False,NaN
251170000,BPAC,blocked premature atrial contraction,blocked premature atrial contraction,False,NaN
426434006,AnMIs,anterior ischemia,anterior ischemia,False,NaN
425856008,PVT,paroxysmal ventricular tachycardia,paroxysmal ventricular tachycardia,False,NaN
425623009,LIs,lateral ischemia,lateral ischaemia,False,NaN
251173003,AB,atrial bigeminy,atrial bigeminy,False,NaN
195126007,AH,atrial hypertrophy,atrial hypertrophy,False,NaN
251168009,SVB,supraventricular bigeminy,supraventricular bigeminy,False,NaN
57054005,AMI,acute myocardial infarction,acute myocardial infarction,False,NaN
82226007,DIB,diffuse intraventricular block,diffuse intraventricular block,False,NaN
81898007,VEsR,ventricular escape rhythm,ventricular escape rhythm,False,NaN
77867006,SQT,shortened qt interval,decreased qt interval,False,NaN
75532003,VEsB,ventricular escape beat,ventricular escape beat,False,NaN
74615001,BTS,tachycardia-bradycardia,brady tachy syndrome,False,NaN
74390002,WPW,wolff-parkinson-white pattern,wolff parkinson white pattern,False,NaN
67198005,PSVT,paroxysmal supraventricular tachycardia,paroxysmal supraventricular tachycardia,False,NaN
65778007,SAB,sinoatrial block,sinoatrial block,False,NaN
60423000,SND,sinus node dysfunction,sinus node dysfunction,False,NaN
55930002,STC,st segment changes,s t changes,False,NaN
89792004,RVH,right ventricular hypertrophy,right ventricular hypertrophy,False,NaN
54329005,AnMI,acute myocardial infarction of anterior wall,anterior myocardial infarction,False,NaN
54016002,MoI,mobitz type i incomplete atrioventricular block,mobitz type i wenckebach atrioventricular block,False,NaN
53741008,CHD,coronary arteriosclerosis,coronary heart disease,False,NaN
49578007,SPRI,shortened pr interval,shortened pr interval,False,NaN
49260003,IR,idioventricular rhythm,idioventricular rhythm,False,NaN
29320008,AVJR,ectopic rhythm,atrioventricular junctional rhythm,False,NaN
27885002,CHB,complete atrioventricular block,complete heart block,False,NaN
13640000,FB,fusion beats,fusion beats,False,NaN
11157007,VBig,ventricular bigeminy,ventricular bigeminy,False,NaN
84114007,HF,heart failure,heart failure,False,NaN
111288001,VFL,ventricular flutter,ventricular flutter,False,NaN
251164006,JPC,junctional premature complex,junctional premature complex,False,NaN
164951009,abQRS,qrs complex abnormal,abnormal QRS,False,NaN
251139008,ALR,suspect arm leads reversed,suspect arm ecg leads reversed,False,NaN
251120003,ILBBB,incomplete left bundle branch block,incomplete left bundle branch block,False,NaN
233917008,AVB,atrioventricular block,av block,False,NaN
204384007,CIAHB,congenital incomplete atrioventricular heart b...,congenital incomplete atrioventricular heart b...,False,NaN
6374002,BBB,bundle branch block,bundle branch block,False,NaN
195101003,WAP,wandering atrial pacemaker,wandering atrial pacemaker,False,NaN
195080001,AFAFL,atrial fibrillation and flutter,atrial fibrillation and flutter,False,NaN
195060002,VPEx,ventricular pre-excitation,ventricular pre excitation,False,NaN
195042002,IIAVB,second degree atrioventricular block,2nd degree av block,False,NaN
164937009,UAb,u wave abnormal,u wave abnormal,False,NaN
164861001,MIs,myocardial ischemia,myocardial ischemia,False,NaN
164931005,STE,st elevation,st elevation,False,NaN
164930006,STIAb,st interval abnormal,st interval abnormal,False,NaN
164921003,RAb,r wave abnormal,r wave abnormal,False,NaN
164896001,VF,ventricular fibrillation,ventricular fibrillation,False,NaN
164895002,VTach,ventricular tachycardia,ventricular tachycardia,False,NaN
164884008,VEB,ventricular ectopics,ventricular ectopics,False,NaN
164873001,LVH,left ventricle hypertrophy,left ventricular hypertrophy,False,NaN
164867002,OldMI,old myocardial infarction,old myocardial infarction,False,NaN
164865005,MI,myocardial infarction,myocardial infarction,False,NaN
67741000119109,LAE,left atrial enlargement,left atrial enlargement,False,NaN

In [24]:
# Check out classes that are note scored
equivalent_classes = [['713427006', '59118001'], ['284470004', '63593006'], ['427172004', '17338001']]

In [25]:
for equ in equivalent_classes:
    print("#" * 50)
    print(df.loc[equ[0]])
    print(df.loc[equ[1]])
    
# By the power nobody appointed me, I decide we go with
# 59118001 (right bundle branch block)
# 284470004 (premature atrial contraction)
# 427172004 (premature ventricular contractions)

##################################################
SHORT                                     CRBBB
SNOMED       complete right bundle branch block
PHYSIONET    complete right bundle branch block
SCORED                                     True
SET                                         NaN
Name: 713427006, dtype: object
SHORT                             RBBB
SNOMED       right bundle branch block
PHYSIONET    right bundle branch block
SCORED                            True
SET                                NaN
Name: 59118001, dtype: object
##################################################
SHORT                                 PAC
SNOMED       premature atrial contraction
PHYSIONET    premature atrial contraction
SCORED                               True
SET                                   NaN
Name: 284470004, dtype: object
SHORT                                    SVPB
SNOMED       supraventricular premature beats
PHYSIONET    supraventricular premature beats
SCORED                                   True
SET                                       NaN
Name: 63593006, dtype: object
##################################################
SHORT                                       PVC
SNOMED       premature ventricular contractions
PHYSIONET    premature ventricular contractions
SCORED                                     True
SET                                         NaN
Name: 427172004, dtype: object
SHORT                                VPB
SNOMED       ventricular premature beats
PHYSIONET    ventricular premature beats
SCORED                              True
SET                                  NaN
Name: 17338001, dtype: object

In [26]:
# New decide if we want to create subsets
df.loc[df['SCORED']]

,SHORT,SNOMED,PHYSIONET,SCORED,SET
426627000,Brady,bradycardia,bradycardia,True,NaN
59118001,RBBB,right bundle branch block,right bundle branch block,True,NaN
164890007,AFL,atrial flutter,atrial flutter,True,NaN
164889003,AF,atrial fibrillation,atrial fibrillation,True,NaN
164917005,QAb,q wave abnormal,qwave abnormal,True,NaN
426177001,SB,sinus bradycardia,sinus bradycardia,True,NaN
284470004,PAC,premature atrial contraction,premature atrial contraction,True,NaN
111975006,LQT,prolonged qt interval,prolonged qt interval,True,NaN
164934002,TAb,t wave abnormal,t wave abnormal,True,NaN
164947007,LPR,prolonged pr interval,prolonged pr interval,True,NaN
270492004,IAVB,first degree atrioventricular block,1st degree av block,True,NaN
426783006,SNR,sinus rhythm,sinus rhythm,True,NaN
427084000,STach,sinus tachycardia,sinus tachycardia,True,NaN
427172004,PVC,premature ventricular contractions,premature ventricular contractions,True,NaN
427393009,SA,sinus arrhythmia,sinus arrhythmia,True,NaN
59931005,TInv,inverted t wave,t wave inversion,True,NaN
63593006,SVPB,supraventricular premature beats,supraventricular premature beats,True,NaN
47665007,RAD,right axis deviation,right axis deviation,True,NaN
698252002,NSIVCB,non-specific intraventricular conduction delay,nonspecific intraventricular conduction disorder,True,NaN
10370003,PR,rhythm from artificial pacing,pacing rhythm,True,NaN
713427006,CRBBB,complete right bundle branch block,complete right bundle branch block,True,NaN
713426002,IRBBB,incomplete right bundle branch block,incomplete right bundle branch block,True,NaN
17338001,VPB,ventricular premature beats,ventricular premature beats,True,NaN
251146004,LQRSV,low qrs voltages,low qrs voltages,True,NaN
39732003,LAD,left axis deviation,left axis deviation,True,NaN
445118002,LAnFB,left anterior fascicular block,left anterior fascicular block,True,NaN
164909002,LBBB,left bundle branch block,left bundle branch block,True,NaN